### ISSUE TITLE
Update IBM SSI API Swagger Definitions for \identities endpoint mentioned in Readme

### ISSUE THREAD

**Issue by iamgollum** [IBM-Blockchain-Identity/verify-creds-samples#10]
When I go to [IBM SSI API swagger](https://swagger.info.verify-creds.com/api/v1/docs/) the identities endpoint is not provided. I imagine this should live under the *General* section.

```
curl -u <account_admin_agent_name>:<account_admin_agent_password> -X PATCH \
    <account_url>/api/v1/identities/<agent_name> \ . <-- HERE!
    -H 'Content-Type: application/json' \
    -d '{ "role": "TRUST_ANCHOR" }'
```

**Comment by joevolleyball** [comment]
Sorry, it should have been noted that /identities is an alias for /agents which will be the direction moving forward.  The next release of the samples will use /agents.  Marking this as WONTFIX.

**Comment by iamgollum** [comment]
@joevolleyball thanks so much!
