### ISSUE TITLE
No Demo Users Button In UI

### ISSUE THREAD

**Issue by iamgollum** [IBM-Blockchain-Identity/verify-creds-samples#8]
I am using this tutorial as part of my enablement for IBM SSI and noticed that the Tutorial seems outdated. In particular the DMV User Account creation is missing the "Demo User" button. When I click Admin I get the following and there is no default admin user / password mentioned in the documentation. At this point I will need to scan through the code and figure out whats going...

<img width="1144" alt="Screen Shot 2019-11-20 at 10 37 08 PM" src="https://user-images.githubusercontent.com/1408766/69302055-55515a80-0be6-11ea-837b-b8263a9a01fa.png">

Note: when I run this locally, the Demo Pager does show up ... so the deployed version is not functioning 100%.

**Comment by wrshome** [comment]
Did you ever get an answer?

**Comment by joevolleyball** [comment]
Sorry that I never responded before.

We are working on getting our latest code ready for delivery which includes revamping verify-creds-samples to run with the new agency code and improved documentation of the samples.  I've already fixed this issue in that branch.  I'll work on correcting it for the current alpha
